language: cpp

compiler:
  - gcc

os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - mkdir build
  - cd build
  - cmake -DTESTS=TRUE ..

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - make
  - make test
